### ISSUE TITLE
Error when creating a new project

### ISSUE THREAD

**Issue by Acheron1** [JulianEberius/SublimeRope#32]
Hi,

if I create a new project I get the following error in the console:

Exception in thread Thread-3:
Traceback (most recent call last):
  File ".\threading.py", line 532, in **bootstrap_inner
  File ".\sublime_rope.py", line 535, in run
    self.ctx.build_cache()
  File "C:\Users\T-400s\Desktop\Sublime\Data\Packages\SublimeRope\ropemate__init**.py", line 87, in build_cache
    self.importer.generate_cache()
  File "C:\Users\T-400s\Desktop\Sublime\Data\Packages\SublimeRope\rope\contrib\autoimport.py", line 94, in generate_cache
    resources = self.project.pycore.get_python_files()
  File "C:\Users\T-400s\Desktop\Sublime\Data\Packages\SublimeRope\rope\base\pycore.py", line 199, in get_python_files
    return [resource for resource in self.project.get_files()
  File "C:\Users\T-400s\Desktop\Sublime\Data\Packages\SublimeRope\rope\base\project.py", line 235, in get_files
    return self.file_list.get_files()
  File "C:\Users\T-400s\Desktop\Sublime\Data\Packages\SublimeRope\rope\base\project.py", line 353, in get_files
    self._add_files(self.project.root)
  File "C:\Users\T-400s\Desktop\Sublime\Data\Packages\SublimeRope\rope\base\project.py", line 357, in _add_files
    for child in folder.get_children():
  File "C:\Users\T-400s\Desktop\Sublime\Data\Packages\SublimeRope\rope\base\resources.py", line 123, in get_children
    if not self.project.is_ignored(child):
  File "C:\Users\T-400s\Desktop\Sublime\Data\Packages\SublimeRope\rope\base\project.py", line 282, in is_ignored
    return self.ignored.does_match(resource)
  File "C:\Users\T-400s\Desktop\Sublime\Data\Packages\SublimeRope\rope\base\resources.py", line 196, in does_match
    for pattern in self.compiled_patterns:
  File "C:\Users\T-400s\Desktop\Sublime\Data\Packages\SublimeRope\rope\base\resources.py", line 210, in compiled_patterns
    self._add_pattern(pattern)
  File "C:\Users\T-400s\Desktop\Sublime\Data\Packages\SublimeRope\rope\base\resources.py", line 193, in _add_pattern
    self.compiled_patterns.append(re.compile(re_pattern))
  File ".\re.py", line 190, in compile
  File ".\re.py", line 245, in _compile
error: multiple repeat

I tried different locations and virtualenv.
I reinstall ST2 und sublimerope but the error stays the same.

It seems like SublimeRobe has a problem with building the cache
but I don't know why.

I am using Windows 7.b

**Comment by DamnWidget** [comment]
I can't reproduce this problem.

Are you using the embedded Python libraries that comes with ST2 or your own?

**Comment by Acheron1** [comment]
I tried both ... python 2.7 + ST2 and just ST2.
I also tried the 32bit and the 64bit version of ST2.

It doesn't matter. The error stays the same.
